on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

name: Publish

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  publish-crate:
    name: Publish
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo publish -p actfv --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
  publish-release-linux:
    name: Publish Release Linux
    runs-on: ubuntu-latest
    needs: [CI]
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build
        run: cargo build --all --release && strip target/release/actfv && mv target/release/actfv target/release/actfv_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/actfv_amd64

  publish-release-win:
    name: Publish Release Windows
    runs-on: windows-latest
    needs: [CI]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build
        run: cargo build --all --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/actfv.exe

  publish-release-mac:
    name: Publish Release Mac
    runs-on: macos-latest
    needs: [CI]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-apple-darwin

      - name: Build for mac
        run: cargo build --all --release && strip target/release/actfv && mv target/release/actfv target/release/actfv_darwin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/actfv_darwin
